name: CI

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install mypy flake8 black pytest pytest-cov pre-commit
        pip install -r requirements.txt

    - name: Lint with pre-commit
      run: |
        pre-commit run --all-files

    - name: Run unit tests and generate coverage report
      run: |
        pytest tests/unit --cov=my_module --cov-report=xml

    - name: Run integration tests
      run: |
        pytest tests/integration

    - name: Check dependencies for security vulnerabilities
      run: |
        pip install safety
        safety check || true

    - name: Publish code coverage
      uses: codecov/codecov-action@v2
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./coverage.xml
